### ISSUE TITLE
[Bug]: BRAT failing to load plugin

### ISSUE THREAD

**Issue by menagerie198** [Quorafind/Obsidian-New-Bullet-With-Time#4]
### Bug Description

BRAT is complaining that there is no manifest.json file, and will not load the plugin

### Obsidian Version

1.0.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
@Quorafind Please try again, I named wrongly when I create the repo, it should be `obsidian` rather than `obsidina`
